import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Item from '@/components/Item'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <div className={`${styles.center} ${styles.name}`}>
            DvirDEV
          </div>
        </div>

        <div className={styles.grid}>
          <Item
            url='https://drive.google.com/file/d/1zOSgtPg2RsRdeDXJ27eF-8dGeU36SCTx/view?usp=sharing'
            icon='person_black_24dp.svg'
            iconWidth={30}
            title='Resume'
          />

          <Item
            url='https://github.com/DvirArazi'
            icon='github-mark.svg'
            iconWidth={25}
            iconHeight={24}
            title='GitHub'
            yOffset={1}
          />
        </div>

        <div className={styles.grid}>
          <Item
            url='https://neo-chess.herokuapp.com/'
            icon='neo-chess.svg'
            iconWidth={25}
            title='Neo-Chess'
            description='A web app for playing an original chess variant online and over the board'
          />

          <Item
            url='http://everybodysjimapp.herokuapp.com/'
            icon='everybodys-jim.svg'
            iconWidth={22}
            title="Everybody's Jim"
            description='A web app implementation of an original multiplayer role-playing game'
            yOffset={3}
          />

          <Item
            url='http://everybodysjimapp.herokuapp.com/'
            icon='/bat.png'
            iconWidth={26}
            title="Castlevania Remake"
            description='A web app implementation of an original multiplayer role-playing game'
            yOffset={3}
          />

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`${inter.className} ${styles.inner}`}>
              Templates
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
